spring:
  profiles:
    active: local
  application:
    name: boardgo

  #jpa
  jpa:
    hibernate:
      ddl-auto: none
    format_sql: true
    show-sql: true

greeting:
  message: This is pre-commit test. I hope this function to work!!!